Feature/add title
DIERYA/ecommerce pull request #1
Opened 2023-11-24 18:10 UTC by DIERYA

- Created and styled categories section

2023-11-24 18:19 UTC, gitFaisal requested changes
Make the changes requested and we should be good to merge!

2023-11-24 18:19 UTC, gitFaisal commented on oasis/src/App.css
> +}
Having a hardcoded min-width of 600px might be the reason our app doesn't adjust to phone screen size. Look into how we can improve this as a homework.

2023-11-24 18:19 UTC, gitFaisal commented on oasis/src/App.css
> +}
The title font is hardcoded, which means on smaller screens the text will be way too large. Look into how we can dynamically change the size of the text to fit different screen sizes.

2023-11-24 18:19 UTC, gitFaisal commented on oasis/src/components/Categories/CategoryStyles.css
> +  flex: 1; /* t items will make them grow or shrink to fill unused*/
Remove comment

2023-11-24 18:19 UTC, gitFaisal commented on oasis/src/components/Navbar/Navbar.jsx
> +      {/* Original Navbar code */}
remove comment

2024-01-28 17:29 UTC, DIERYA commented on oasis/src/App.css
> +}
👍

2024-01-28 17:30 UTC, DIERYA commented on oasis/src/App.css
> +}
👍

2024-01-28 17:32 UTC, DIERYA commented on oasis/src/components/Categories/CategoryStyles.css
> +  flex: 1; /* t items will make them grow or shrink to fill unused*/
👍

2024-01-28 17:32 UTC, DIERYA commented on oasis/src/components/Navbar/Navbar.jsx
> +      {/* Original Navbar code */}
👍

2024-01-28 18:07 UTC, gitFaisal approved these changes

2024-01-28 18:07 UTC, merged